// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNidEwKpmpnxrVMDrgEGB1BGuXcUDMfCI',
    appId: '1:713149608513:web:92dd6a72acb17e9f50ccc0',
    messagingSenderId: '713149608513',
    projectId: 'camposimples10-c1a2f',
    authDomain: 'camposimples10-c1a2f.firebaseapp.com',
    storageBucket: 'camposimples10-c1a2f.appspot.com',
    measurementId: 'G-2MKVWZWY9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9sLrqiTdJN-p8w35c9n-Bc096h4flo5o',
    appId: '1:713149608513:android:510f24273292255450ccc0',
    messagingSenderId: '713149608513',
    projectId: 'camposimples10-c1a2f',
    storageBucket: 'camposimples10-c1a2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7-iwlDFA0LnYdlKqEyosLR5nDa8CW5EE',
    appId: '1:713149608513:ios:9e690beaa6f7630450ccc0',
    messagingSenderId: '713149608513',
    projectId: 'camposimples10-c1a2f',
    storageBucket: 'camposimples10-c1a2f.appspot.com',
    iosBundleId: 'com.example.projetoV1',
  );

}